name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn global add vercel@latest
      - name: Run alias
        run: env && vercel alias --token=$VERCEL_CLI_TOKEN set $BASE_URL staging.jprojects.dev --scope=$VERCEL_SCOPE
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}